let items = [
  {
    id: 1,
    name: "clock",
    image: "./assets/img/painting/clock.jpg",
    price: "R$400,00",
    type: "paintings",
  },
  {
    id: 2,
    name: "gamepad",
    image: "./assets/img/painting/gamepad.jpg",
    price: "R$125,00",
    type: "paintings",
  },
  {
    id: 3,
    name: "personagem",
    image: "./assets/img/painting/personagem.jpg",
    price: "R$35,00",
    type: "paintings",
  },
  {
    id: 4,
    name: "clock",
    image: "./assets/img/painting/clock.jpg",
    price: "R$400,00",
    type: "paintings",
  },
  {
    id: 5,
    name: "gamepad",
    image: "./assets/img/painting/gamepad.jpg",
    price: "R$125,00",
    type: "paintings",
  },
  {
    id: 6,
    name: "personagem",
    image: "./assets/img/painting/personagem.jpg",
    price: "R$35,00",
    type: "paintings",
  },
  {
    id: 7,
    name: "clock",
    image: "./assets/img/painting/clock.jpg",
    price: "R$400,00",
    type: "paintings",
  },
  {
    id: 8,
    name: "gamepad",
    image: "./assets/img/painting/gamepad.jpg",
    price: "R$125,00",
    type: "paintings",
  },
  {
    id: 9,
    name: "personagem",
    image: "./assets/img/painting/personagem.jpg",
    price: "R$35,00",
    type: "paintings",
  },
  {
    id: 10,
    name: "clock",
    image: "./assets/img/painting/clock.jpg",
    price: "R$400,00",
    type: "paintings",
  },
  {
    id: 11,
    name: "gamepad",
    image: "./assets/img/painting/gamepad.jpg",
    price: "R$125,00",
    type: "paintings",
  },
  {
    id: 12,
    name: "personagem",
    image: "./assets/img/painting/personagem.jpg",
    price: "R$35,00",
    type: "paintings",
  },
  {
    id: 13,
    name: "anime woman",
    image: "./assets/img/actions/animewoman.jpg",
    price: "R$15,00",
    type: "actions",
  },
  {
    id: 14,
    name: "dragonball personagem",
    image: "./assets/img/actions/dragonballpersonagem.jpg",
    price: "R$15,00",
    type: "actions",
  },
  {
    id: 15,
    name: "starwars personagem",
    image: "./assets/img/actions/starwarspersonagem.jpg",
    price: "R$15,00",
    type: "actions",
  },
  {
    id: 16,
    name: "anime woman",
    image: "./assets/img/actions/animewoman.jpg",
    price: "R$15,00",
    type: "actions",
  },
  {
    id: 17,
    name: "dragonball personagem",
    image: "./assets/img/actions/dragonballpersonagem.jpg",
    price: "R$15,00",
    type: "actions",
  },
  {
    id: 18,
    name: "starwars personagem",
    image: "./assets/img/actions/starwarspersonagem.jpg",
    price: "R$15,00",
    type: "actions",
  },
  {
    id: 19,
    name: "anime woman",
    image: "./assets/img/actions/animewoman.jpg",
    price: "R$15,00",
    type: "actions",
  },
  {
    id: 20,
    name: "dragonball personagem",
    image: "./assets/img/actions/dragonballpersonagem.jpg",
    price: "R$15,00",
    type: "actions",
  },
  {
    id: 21,
    name: "starwars personagem",
    image: "./assets/img/actions/starwarspersonagem.jpg",
    price: "R$15,00",
    type: "actions",
  },
  {
    id: 22,
    name: "anime woman",
    image: "./assets/img/actions/animewoman.jpg",
    price: "R$15,00",
    type: "actions",
  },
  {
    id: 23,
    name: "dragonball personagem",
    image: "./assets/img/actions/dragonballpersonagem.jpg",
    price: "R$15,00",
    type: "actions",
  },
  {
    id: 24,
    name: "starwars personagem",
    image: "./assets/img/actions/starwarspersonagem.jpg",
    price: "R$15,00",
    type: "actions",
  },
];

// console.log(items);
